\hypertarget{classerror__already__set}{}\doxysection{error\+\_\+already\+\_\+set Class Reference}
\label{classerror__already__set}\index{error\_already\_set@{error\_already\_set}}


Fetch and hold an error which was already set in Python.  




{\ttfamily \#include $<$common.\+h$>$}

Inheritance diagram for error\+\_\+already\+\_\+set\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classerror__already__set}
\end{center}
\end{figure}
\doxysubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classerror__already__set_a9f6456fb9f03460d943682037132e819}{error\+\_\+already\+\_\+set}} ()
\item 
\mbox{\hyperlink{classerror__already__set_a91515dabb6445d8ec80bfe04cbed26db}{error\+\_\+already\+\_\+set}} (const \mbox{\hyperlink{classerror__already__set}{error\+\_\+already\+\_\+set}} \&)=delete
\item 
\mbox{\hyperlink{classerror__already__set_a4b9602235c8b02687d50ac2d7354eb05}{error\+\_\+already\+\_\+set}} (\mbox{\hyperlink{classerror__already__set}{error\+\_\+already\+\_\+set}} \&\&e)
\item 
\mbox{\hyperlink{classerror__already__set_a18ad333137ef5b23916ff207a38e9a6a}{$\sim$error\+\_\+already\+\_\+set}} ()
\item 
\mbox{\hyperlink{classerror__already__set}{error\+\_\+already\+\_\+set}} \& \mbox{\hyperlink{classerror__already__set_a06d355a3c4cc9e167cdbdee0b62df6e9}{operator=}} (const \mbox{\hyperlink{classerror__already__set}{error\+\_\+already\+\_\+set}} \&)=delete
\item 
void \mbox{\hyperlink{classerror__already__set_a751b231e5c796447d867cf30007a7fc0}{restore}} ()
\begin{DoxyCompactList}\small\item\em Give the error back to Python. \end{DoxyCompactList}\item 
void \mbox{\hyperlink{classerror__already__set_a471237e45e4049e9e9ec4bc049621eb1}{clear}} ()
\begin{DoxyCompactList}\small\item\em Clear the held Python error state (the C++ {\ttfamily what()} message remains intact) \end{DoxyCompactList}\item 
bool \mbox{\hyperlink{classerror__already__set_ab46d64e46360c5d5528402cb83d9437a}{matches}} (Py\+Object $\ast$ex) const
\begin{DoxyCompactList}\small\item\em Check if the trapped exception matches a given Python exception class. \end{DoxyCompactList}\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
Fetch and hold an error which was already set in Python. 

\doxysubsection{Constructor \& Destructor Documentation}
\mbox{\Hypertarget{classerror__already__set_a9f6456fb9f03460d943682037132e819}\label{classerror__already__set_a9f6456fb9f03460d943682037132e819}} 
\index{error\_already\_set@{error\_already\_set}!error\_already\_set@{error\_already\_set}}
\index{error\_already\_set@{error\_already\_set}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{error\_already\_set()}{error\_already\_set()}\hspace{0.1cm}{\footnotesize\ttfamily [1/3]}}
{\footnotesize\ttfamily error\+\_\+already\+\_\+set\+::error\+\_\+already\+\_\+set (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}

\mbox{\Hypertarget{classerror__already__set_a91515dabb6445d8ec80bfe04cbed26db}\label{classerror__already__set_a91515dabb6445d8ec80bfe04cbed26db}} 
\index{error\_already\_set@{error\_already\_set}!error\_already\_set@{error\_already\_set}}
\index{error\_already\_set@{error\_already\_set}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{error\_already\_set()}{error\_already\_set()}\hspace{0.1cm}{\footnotesize\ttfamily [2/3]}}
{\footnotesize\ttfamily error\+\_\+already\+\_\+set\+::error\+\_\+already\+\_\+set (\begin{DoxyParamCaption}\item[{const \mbox{\hyperlink{classerror__already__set}{error\+\_\+already\+\_\+set}} \&}]{ }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [delete]}}

\mbox{\Hypertarget{classerror__already__set_a4b9602235c8b02687d50ac2d7354eb05}\label{classerror__already__set_a4b9602235c8b02687d50ac2d7354eb05}} 
\index{error\_already\_set@{error\_already\_set}!error\_already\_set@{error\_already\_set}}
\index{error\_already\_set@{error\_already\_set}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{error\_already\_set()}{error\_already\_set()}\hspace{0.1cm}{\footnotesize\ttfamily [3/3]}}
{\footnotesize\ttfamily error\+\_\+already\+\_\+set\+::error\+\_\+already\+\_\+set (\begin{DoxyParamCaption}\item[{\mbox{\hyperlink{classerror__already__set}{error\+\_\+already\+\_\+set}} \&\&}]{e }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}

\mbox{\Hypertarget{classerror__already__set_a18ad333137ef5b23916ff207a38e9a6a}\label{classerror__already__set_a18ad333137ef5b23916ff207a38e9a6a}} 
\index{error\_already\_set@{error\_already\_set}!````~error\_already\_set@{$\sim$error\_already\_set}}
\index{````~error\_already\_set@{$\sim$error\_already\_set}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{$\sim$error\_already\_set()}{~error\_already\_set()}}
{\footnotesize\ttfamily error\+\_\+already\+\_\+set\+::$\sim$error\+\_\+already\+\_\+set (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}



\doxysubsection{Member Function Documentation}
\mbox{\Hypertarget{classerror__already__set_a471237e45e4049e9e9ec4bc049621eb1}\label{classerror__already__set_a471237e45e4049e9e9ec4bc049621eb1}} 
\index{error\_already\_set@{error\_already\_set}!clear@{clear}}
\index{clear@{clear}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{clear()}{clear()}}
{\footnotesize\ttfamily void error\+\_\+already\+\_\+set\+::clear (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}



Clear the held Python error state (the C++ {\ttfamily what()} message remains intact) 

\mbox{\Hypertarget{classerror__already__set_ab46d64e46360c5d5528402cb83d9437a}\label{classerror__already__set_ab46d64e46360c5d5528402cb83d9437a}} 
\index{error\_already\_set@{error\_already\_set}!matches@{matches}}
\index{matches@{matches}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{matches()}{matches()}}
{\footnotesize\ttfamily bool error\+\_\+already\+\_\+set\+::matches (\begin{DoxyParamCaption}\item[{Py\+Object $\ast$}]{ex }\end{DoxyParamCaption}) const\hspace{0.3cm}{\ttfamily [inline]}}



Check if the trapped exception matches a given Python exception class. 

\mbox{\Hypertarget{classerror__already__set_a06d355a3c4cc9e167cdbdee0b62df6e9}\label{classerror__already__set_a06d355a3c4cc9e167cdbdee0b62df6e9}} 
\index{error\_already\_set@{error\_already\_set}!operator=@{operator=}}
\index{operator=@{operator=}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{operator=()}{operator=()}}
{\footnotesize\ttfamily \mbox{\hyperlink{classerror__already__set}{error\+\_\+already\+\_\+set}}\& error\+\_\+already\+\_\+set\+::operator= (\begin{DoxyParamCaption}\item[{const \mbox{\hyperlink{classerror__already__set}{error\+\_\+already\+\_\+set}} \&}]{ }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [delete]}}

\mbox{\Hypertarget{classerror__already__set_a751b231e5c796447d867cf30007a7fc0}\label{classerror__already__set_a751b231e5c796447d867cf30007a7fc0}} 
\index{error\_already\_set@{error\_already\_set}!restore@{restore}}
\index{restore@{restore}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{restore()}{restore()}}
{\footnotesize\ttfamily void error\+\_\+already\+\_\+set\+::restore (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}



Give the error back to Python. 



The documentation for this class was generated from the following files\+:\begin{DoxyCompactItemize}
\item 
C\+:/\+Users/nouet/\+Documents/\+Cours/5\+A/\+Dev PRD/\+Prd\+Coprod/\+Prd\+Coprod/libs/xlnt-\/1.\+5.\+0/third-\/party/pybind11/include/pybind11/\mbox{\hyperlink{common_8h}{common.\+h}}\item 
C\+:/\+Users/nouet/\+Documents/\+Cours/5\+A/\+Dev PRD/\+Prd\+Coprod/\+Prd\+Coprod/libs/xlnt-\/1.\+5.\+0/third-\/party/pybind11/include/pybind11/\mbox{\hyperlink{pybind11_8h}{pybind11.\+h}}\end{DoxyCompactItemize}
